### ISSUE TITLE
Export accounts

### ISSUE THREAD

**Issue by Madis0** [arturogutierrez/Openticator#74]
I see that you have a sync feature planned, but what about adding an export feature so we could choose where to store it by ourselves? The file could be encrypted by the master password users already have to set in the app.

**Comment by arturogutierrez** [comment]
Yes, I have it in mind and I'm working when I have some time. In fact, there is a branch where I already have the welcome screen changed to use Firebase login, I want to store the all data in the cloud using Firebase but encrypted by the master password (and, of course, the master password is not stored in the cloud), so nobody will be able to access your data without the master password.
